services:
  # A Docker web service
  
 services:
  - type: web
    name: 2050ai-website  # Choose a name for your service
    runtime: static
    routes:
      - path: /
        rewrite: /index.html

    staticPublishPath: . #  Publish static files from the root directory
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
